run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m
  skip-files:
    - "cmd/survey/*"
linters:
  disable-all: true
  enable:
    # enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # disabled by default
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    # - deadcode [deprecated]
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct [deprecated]
    # - exhaustruct
    - exportloopref
    # - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot
    - godox
    # - goerr113
    - gofmt
    # - gofumpt
    - goheader
    - goimports
    # - golint [deprecated]
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    # - gosmopolitan
    - grouper
    # - ifshort [deprecated]
    - importas
    - interfacebloat
    # - interfacer [deprecated]
    # - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    # - maligned [deprecated]
    # - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosnakecase [deprecated]
    - nosprintfhostport
    # - paralleltest
    - prealloc
    # - predeclared
    - promlinter
    - reassign
    - revive
    # - rowserrcheck
    # - scopelint [deprecated]
    - sqlclosecheck
    # - structcheck [deprecated]
    - stylecheck
    # - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    # - testpackage
    # - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # - varcheck [deprecated]
    # - varnamelen
    # - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint

# all available settings of specific linters
linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 150
    # Tab width in spaces.
    # Default: 1
    tab-width: 1
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 16
  errorlint:
    # Check for plain error comparisons.
    # Default: true
    comparison: false
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/s12chung/text2anki) # Custom section: groups all imports with the specified Prefix.
  tagliatelle:
    # Check the struct tag name case.
    case:
      # `camel` is used for `json` and `yaml`, and `header` is used for `header` (can be overridden)
      # Default: {}
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`
        json: snake
issues:
  # golangci has its own rules to ignore certain lint rules. See `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  exclude-rules:
    # code for humans instead of machines until you scale up
    - text: fieldalignment
      linters:
        - govet
    # I like my zeros
    - text: "var-declaration: should drop = 0 from declaration of var"
      linters:
        - revive
    # easier to manipulate, even if longer
    - text: "if-return: redundant if ...; err != nil check, just return error instead"
      linters:
        - revive
