// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import ()

type Term struct {
	Text         string
	Variants     string
	PartOfSpeech string
	CommonLevel  string
	Translations string
	Popularity   string
}
