#!/usr/bin/env ruby

ZIP_DIR = File.expand_path('~/Downloads')
DEST_DIR = File.expand_path('~/Library/Application Support/Anki2/User 1/collection.media')
ZIP_EXT = '.zip'

zip_file_path = Dir.glob("#{ZIP_DIR}/text2anki-*" + ZIP_EXT).sort_by do |path|
    path.split('-').last.chomp(ZIP_EXT)[0..7].to_i(16)
end.first
if zip_file_path.nil?
    puts "Zip file not found"
    exit -1
end

unzip_dir = zip_file_path.chomp(ZIP_EXT)
if File.exist?(unzip_dir)
    puts "Skipping unzip, path exists: #{unzip_dir}"
else
    system("unzip #{zip_file_path} -d #{unzip_dir}")
end

puts ""

files_dir = File.join(unzip_dir, 'files')
if !File.exist?(files_dir)
    puts "Skipping copying media files, path does not exist: #{files_dir}"
else
    puts "Copying media files"
    Dir.foreach(files_dir) do |file_name|
        next if ['.', '..'].include?(file_name)
        source_path = File.join(files_dir, file_name)
        dest_path = File.join(DEST_DIR, file_name)
      
        if File.exist?(dest_path)
          puts "File already exists, skipping: #{dest_path}"
          next
        end
        IO.copy_stream(source_path, dest_path)
        puts "Copied: #{dest_path}"
      end
end

system("open #{unzip_dir}")