name: Go

on:
  push:
    paths-ignore:
      - ui/**

env:
  CI: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: "go.mod"

      - name: Cache Setup
        id: cache-setup
        uses: actions/cache@v3
        env:
          cache-name: cache-setup
        with:
          path: .github/bin/*
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Makefile*', '**/*.mk') }}
      - if: ${{ steps.cache-setup.outputs.cache-hit != 'true' }}
        name: Setup
        run: make ci.setup

      - name: Build
        run: make ci.build
      - name: Diff
        run: make ci.diff
      - name: Test
        run: make ci.test